### PR TITLE
feat: new changes

### PR DESCRIPTION
**Pull request by oksourav**
1. Removed all unnecessary files.
2. Updated with correct information

### CODE REVIEW

**Comment by oksourav** [comment]
Deployed Changes URL - https://bsides-hyd-demo.onrender.com/

**Comment by sagarbhure** [comment]
Can you schedule a review call between three of us?

**Comment by msnishanth9001** [comment]
are we doing instagram social? If yes need to add that

**Comment by msnishanth9001** [comment]
Workshop and Training. 2 Items we can have if feasible.

**Comment by msnishanth9001** [comment]
Review Comments

- Change logo width.
- update location to > __
- meet up tab > placeholder.
- add navigation bar with Home. Meet-up Schedule.

- we can probably remove Phone as mandatory field, in contact us.
- Workshop and Training. 2 Items we can have if feasible.
- are we doing Instagram social? If yes need to add that

**Review by msnishanth9001 — COMMENTED** [review]
- [x] Change logo width.
- [ ]  update location to > __
- [ ]  meet up tab > placeholder.
- [ ]  add navigation bar with Home. Meet-up Schedule.
- [x]  we can probably remove Phone as mandatory field, in contact us.
- [x]  Workshop and Training. 2 Items we can have if feasible.
- [x]  are we doing Instagram social? If yes need to add that.
- [x]  Nav Icon, for the tab. Remove the BKG and make it as PNG.
- [x]  delete [readme.txt](https://github.com/BSides-Hyderabad/BSides-Website/blob/master/readme.txt)

**Comment by msnishanth9001** [comment]
- [ ] In Contact US. The Messages should not be empty... else It will be empty email.
- [ ] The interested Can be made mandatory. Will help tag/ sort emails.
- [ ]  Can we replace this with, "Stay tuned for the venue (TBD)" with "Stay tuned for Event details." This is more Generic for the Home Page.

**Comment by oksourav** [comment]
@msnishanth9001 `In Contact US. The Messages should not be empty... else It will be empty email.` We are not sending the email. Everyone will not be interested in writing messages for that reason I have made it optional.

**Comment by msnishanth9001** [comment]
@oksourav I did not understand. Then what is the point of contacting.

**Comment by oksourav** [comment]
@msnishanth9001 Generally User takes very few minutes to submit the form & also some people usually skip the messages or add some random messages. So I have added it to collect additional information. I don't see it as a mandatory field. @sagarbhure @msnishanth9001 If you really want to make the field mandatory I'm also ok with it.

**Review by sagarbhure — APPROVED** [review]

**Comment by msnishanth9001** [comment]
fixes #3

**Pull request merged**
